Add spell-check to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,3 +47,19 @@ jobs:
             [2]: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs
           branch: formula
         if: github.event_name == 'schedule' && steps.diff.outputs.success == 'false'
+
+  spell-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - run: npx cspell --no-progress $(git ls-files)
+      - name: Check duplications in dictionary
+        run: |
+          dup=$(sed '/^$/d' .github/.cspell/dictionary.txt | LC_ALL=C sort -f | uniq -d -i)
+          if [[ -n "${dup}" ]]; then
+              echo "error: duplicated words in .github/.cspell/dictionary.txt"
+              echo "======================================="
+              echo "${dup}"
+              echo "======================================="
+              exit 1
+          fi
